### ISSUE TITLE
Wipe all local sessions

### ISSUE THREAD

**Issue by fox-md** [c6o/roadmap#38] opened 2022-01-12 10:07 UTC
### Question

Hi,
Can you please advise, how can I remove all local sessions?

### Sample Code

Currently `session list` states that there is one local session

```
# czctl session list

There are 1 local sessions found:
     Mounted volumes from nginx80-7b475d48dd-45nz9
```

```
# czctl session close
✖  Ensuring Session parameters                                                     Failed!
✖   Closing session 'Mounted volumes from nginx80-7b475d48dd-45nz9'                Failed!
✔    Ensuring Mount Parameters                                                     Done
✖     Unmounting volumes from nginx80-7b475d48dd-45nz9                             Failed!
✖     Removing NFS server for default                                              Failed!
Could not find nginx80-7b475d48dd-45nz9 in default
Could not find nginx80-7b475d48dd-45nz9 in default
```
Currently pod does not exist, so jobs fails. I tried to restart czctl, restarted workstation, but this sessions still appears in the list.

**Comment by conneryn** [comment] 2022-01-13 23:12
Thanks for reporting this.

We are looking into the root cause of why closing the session is failing, and into ways to prevent it from getting into this state in the future.  We are also in the process of adding a `--force` type flag to the `session close`, which will allow for a more forceful closing of sessions, to address these sorts of situations.

In the meantime, to get you unstuck now, we do also have an internal flag to help reset your environment via `czctl session close --purge`, but this flag is not guaranteed to stay around in future versions, and should not be a go-to solution.  It will be replaced soon by the safer/more-graceful `--force` flag mentioned above.  Let me know if that's able to get you going again.

Many thanks,
Connery

**Closed** 2023-11-16 22:19 UTC
Labels: question, wontfix, anvil
